---
- name: Install Galaxy setup role for Hyperfoil
  shell: ansible-galaxy install hyperfoil.hyperfoil_setup,0.5
- name: Install Galaxy shutdown role for Hyperfoil
  shell: ansible-galaxy install hyperfoil.hyperfoil_shutdown,0.5
- name: Install Galaxy install role for Hyperfoil
  shell: ansible-galaxy install hyperfoil.hyperfoil_test,0.5
- name: Install Galaxy roles for Hyperfoil
  shell: ansible-galaxy install hyperfoil.hyperfoil_generate_report,0.0.1